import { useState, useRef } from "react";
import Navbar from "../components/NavbarLogin";
import "../styles/ResumeAnalyzer.css";

export default function ResumeAnalyzer() {
  const user = JSON.parse(localStorage.getItem("user"));
  const [role, setRole] = useState("");
  const [file, setFile] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const reportRef = useRef(null);

  function handleFileChange(e) {
    const selected = e.target.files[0];
    if (selected && selected.type !== "application/pdf") {
      alert("Only PDF Resume Allowed!");
      return;
    }
    setFile(selected);
  }

  async function handleAnalyze() {
    if (!user || !user._id) {
      alert("Please Login First");
      return;
    }

    if (!file || !role.trim()) {
      alert("Enter Role & Upload Resume");
      return;
    }

    setLoading(true);
    setResult(null);

    try {
      const formData = new FormData();
      formData.append("resume", file);
      formData.append("role", role);

      const res = await fetch(
        `http://127.0.0.1:5000/api/analyze-resume/${user._id}`,
        { method: "POST", body: formData }
      );

      const data = await res.json();

      if (data.success) {
        setResult(data.analysis);
      } else {
        alert("Analysis Failed");
      }
    } catch (err) {
      console.log(err);
      alert("Server Error");
    }

    setLoading(false);
  }

  function downloadPDF() {
    if (!result || !reportRef.current) return;

    const printWindow = window.open("", "_blank");
    const content = reportRef.current.innerHTML;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Resume Analysis Report</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body {
            font-family: 'Inter', 'Segoe UI', sans-serif;
            padding: 40px;
            background: #0a0f1a;
          }
          .report-container { max-width: 1000px; margin: 0 auto; }
          .header {
            text-align: center;
            padding: 30px;
            background: linear-gradient(135deg, #5b8c5a, #3d6b3c);
            color: white;
            border-radius: 16px;
            margin-bottom: 30px;
          }
          .header h1 { font-size: 24px; margin-bottom: 8px; }
          .date { margin-top: 10px; font-size: 12px; opacity: 0.8; }
          .score-grid { display: grid; grid-template-columns: repeat(4,1fr); gap: 16px; margin-bottom: 30px; }
          .score-card {
            background: #1a1f2e;
            padding: 20px;
            border-radius: 12px;
            text-align: center;
            border-left: 4px solid #5b8c5a;
          }
          .score-value { font-size: 28px; font-weight: bold; color: #5b8c5a; }
          .score-label { font-size: 12px; color: #8a9bb5; margin-top: 8px; }
          .section { margin-bottom: 24px; border-bottom: 1px solid #2a2f3e; padding-bottom: 16px; }
          .section-title { font-size: 18px; font-weight: 600; color: #e0e0e0; margin-bottom: 16px; }
          .skills-list { display: flex; flex-wrap: wrap; gap: 8px; }
          .skill {
            background: #1a1f2e;
            padding: 6px 14px;
            border-radius: 20px;
            font-size: 12px;
          }
          .skill.matched { color: #5b8c5a; border: 1px solid #5b8c5a; }
          .skill.missing { color: #e74c3c; border: 1px solid #e74c3c; }
          .recommendations { list-style: none; padding: 0; }
          .recommendations li {
            padding: 10px;
            margin: 8px 0;
            background: #1a1f2e;
            border-radius: 8px;
            border-left: 3px solid #5b8c5a;
          }
          .footer { text-align: center; padding: 20px; font-size: 11px; color: #5a6e8a; margin-top: 30px; }
        </style>
      </head>
      <body>
        <div class="report-container">${content}<div class="footer"><p>Generated by HireSense - Intelligent Support System</p></div></div>
        <script>window.onload = () => { window.print(); window.close(); };</script>
      </body>
      </html>
    `);
    printWindow.document.close();
  }

  return (
    <div className="analyzer-page">
      <Navbar />
      <div className="analyzer-container">
        <div className="analyzer-grid">
          
          {/* LEFT SIDE - FORM AND RESULTS */}
          <div className="analyzer-card">
            <div className="analyzer-header">
              <h1 className="analyzer-title">Resume Analyzer</h1>
              <p className="analyzer-subtitle">AI-powered insights to optimize your resume</p>
            </div>

            <div className="analyzer-form">
              <div className="input-group">
                <label className="input-label">Target Job Role</label>
                <input
                  type="text"
                  className="role-input"
                  placeholder="e.g., Software Engineer, Data Scientist"
                  value={role}
                  onChange={(e) => setRole(e.target.value)}
                />
              </div>

              <div className="input-group">
                <label className="input-label">Upload Resume (PDF)</label>
                <div className="file-wrapper">
                  <input
                    type="file"
                    id="resume-upload"
                    accept=".pdf"
                    onChange={handleFileChange}
                    className="file-hidden"
                  />
                  <label htmlFor="resume-upload" className="file-btn">
                    {file ? file.name : "Choose PDF File"}
                  </label>
                  {file && <span className="file-status">Ready to analyze</span>}
                </div>
              </div>

              <button
                className={`analyze-btn ${loading ? "loading" : ""}`}
                onClick={handleAnalyze}
                disabled={loading}
              >
                {loading ? "Analyzing..." : "Analyze Resume"}
              </button>
            </div>

            {result && (
              <div className="analyzer-results" ref={reportRef}>
                <div className="stats-row">
                  <div className="stat-card">
                    <span className="stat-value">{result.scores?.ats_compatibility || 0}%</span>
                    <span className="stat-label">ATS</span>
                  </div>
                  <div className="stat-card">
                    <span className="stat-value">{result.scores?.job_match_rate || 0}%</span>
                    <span className="stat-label">Job Match</span>
                  </div>
                  <div className="stat-card">
                    <span className="stat-value">{result.scores?.ranking_score || 0}%</span>
                    <span className="stat-label">Overall</span>
                  </div>
                  <div className="stat-card">
                    <span className="stat-value">{result.skills_analysis?.match_percentage || 0}%</span>
                    <span className="stat-label">Skills</span>
                  </div>
                </div>

                <div className="analysis-block">
                  <h3 className="block-title">Skills Analysis</h3>
                  <div className="skills-panel">
                    <div className="skills-col">
                      <h4>Matched Skills</h4>
                      <div className="skills-list">
                        {result.skills_analysis?.matched_skills?.map((s, i) => (
                          <span key={i} className="skill matched">{s}</span>
                        ))}
                        {!result.skills_analysis?.matched_skills?.length && (
                          <p className="empty-msg">None found</p>
                        )}
                      </div>
                    </div>
                    <div className="skills-col">
                      <h4>Missing Skills</h4>
                      <div className="skills-list">
                        {result.skills_analysis?.missing_skills?.map((s, i) => (
                          <span key={i} className="skill missing">{s}</span>
                        ))}
                        {!result.skills_analysis?.missing_skills?.length && (
                          <p className="empty-msg success">None critical</p>
                        )}
                      </div>
                    </div>
                  </div>
                  <div className="match-progress">
                    <span>Match Rate: {result.skills_analysis?.match_percentage || 0}%</span>
                    <div className="progress-track">
                      <div className="progress-fill" style={{ width: `${result.skills_analysis?.match_percentage || 0}%` }}></div>
                    </div>
                  </div>
                </div>

                <div className="analysis-block">
                  <h3 className="block-title">Quality Check</h3>
                  <div className="quality-row">
                    <span>Grammar Errors:</span>
                    <strong className={result.content_issues?.grammar_errors > 10 ? "warning" : "success"}>
                      {result.content_issues?.grammar_errors || 0}
                    </strong>
                  </div>
                  {result.content_issues?.grammar_details?.length > 0 && (
                    <div className="grammar-list">
                      <h4>Issues Found</h4>
                      {result.content_issues.grammar_details.slice(0, 3).map((err, i) => (
                        <div key={i} className="grammar-item">
                          <span className="grammar-line">Line {err.line_number || "?"}:</span>
                          <span>{err.message}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                {result.content_issues?.formatting_issues?.length > 0 && (
                  <div className="analysis-block">
                    <h3 className="block-title">Formatting Issues</h3>
                    <ul className="issues-list">
                      {result.content_issues.formatting_issues.slice(0, 4).map((issue, i) => (
                        <li key={i}>{issue}</li>
                      ))}
                    </ul>
                  </div>
                )}

                <div className="analysis-block highlight">
                  <h3 className="block-title">Recommendations</h3>
                  <ul className="recommendations-list">
                    {result.recommendations?.slice(0, 5).map((rec, i) => (
                      <li key={i}>{rec}</li>
                    ))}
                  </ul>
                </div>

                <button className="download-report-btn" onClick={downloadPDF}>
                  Download Report (PDF)
                </button>
              </div>
            )}
          </div>

          {/* RIGHT SIDE - INFO PANEL */}
          <div className="info-panel">
            <div className="info-card">
              <h2>Why Analyze Your Resume?</h2>
              <ul>
                <li>ATS Compatibility Score</li>
                <li>Skills Gap Analysis</li>
                <li>Grammar & Formatting Check</li>
                <li>Job-Specific Recommendations</li>
                <li>Downloadable Report</li>
              </ul>
              <div className="info-divider"></div>
              <h3>How It Works</h3>
              <ol>
                <li>Enter your target job role</li>
                <li>Upload your PDF resume</li>
                <li>Get instant AI-powered analysis</li>
                <li>Improve and re-upload</li>
              </ol>
              <div className="info-quote">
                “Your resume is your ticket. Make it first-class.”
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}